// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAppsMappe3.Models;

namespace WebAppsMappe3.Migrations
{
    [DbContext(typeof(DB))]
    [Migration("20181112074621_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebAppsMappe3.Models.FAQ", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("answer");

                    b.Property<string>("question");

                    b.HasKey("Id");

                    b.ToTable("FAQ");

                    b.HasData(
                        new { Id = 1, answer = "Click the sign up button in the upper right corner of the screen.", question = "How do i create a user?" },
                        new { Id = 2, answer = "Press the logout button.", question = "How can i sign out?" },
                        new { Id = 3, answer = "No.", question = "Does this FAQ answer any legitimate questions?" }
                    );
                });

            modelBuilder.Entity("WebAppsMappe3.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("answer");

                    b.Property<string>("asker");

                    b.Property<string>("question");

                    b.Property<string>("replier");

                    b.Property<int>("voteDown");

                    b.Property<int>("voteUp");

                    b.HasKey("Id");

                    b.ToTable("Question");
                });
#pragma warning restore 612, 618
        }
    }
}
